### ISSUE TITLE
faster then https://github.com/yaleh/Flora_Pac

### ISSUE THREAD

**Issue by hnboy2005** [blackgear/mono_pac#8]
faster than https://github.com/yaleh/Flora_Pac  ? just curious

**Comment by blackgear** [comment]
Of course.

The PAC instance will be reuse instead of start new instance for every request. Yaleh's Flora_Pac will redefine ip range array every time but mono_pac do it once.

By the way, Yaleh's Flora_Pac(without blacklist or whitelist) is 7.2x larger than mono_pac and 13.1x larger than mono_pac with unicode compress.
